kind: pipeline
name: deploy

steps:
  - name: compile
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    commands:
      - dotnet publish -c build

  - name: push-image
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: jeremyaherzog/harambe-trader
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}

  - name: deploy
    image: hashicorp/terraform
    environment:
      DO_TOKEN:  
        from_secret: DO_TOKEN
      BROKER_API_KEY_ID:  
        from_secret: BROKER_API_KEY_ID
      BROKER_API_KEY_SECRET:  
        from_secret: BROKER_API_KEY_SECRET
      DATASOURCE_TOKEN:  
        from_secret: DATASOURCE_TOKEN
      DATABASE_CONNECTION_STRING:  
        from_secret: DATABASE_CONNECTION_STRING
      TF_STATE_ACCESS_KEY:
        from_secret: TF_STATE_ACCESS_KEY
      TF_STATE_SECRET_KEY:
        from_secret: TF_STATE_SECRET_KEY
    commands:
      - apk add --update make
      - printenv > .env
      - make init
      - printf 'yes' | make deploy VERSION=$DRONE_COMMIT_SHA
